name: Keep Render Apps Alive

on:
  schedule:
    - cron: '*/14 * * * *' # Runs every 14 minutes

jobs:
  keep_alive:
    runs-on: ubuntu-latest

    steps:
    - name: Wake up Render Apps (No Wait)
      run: |
        #!/bin/bash
        curl --fail-with-body https://gemini-ai-bnxm.onrender.com/api/test &
        curl --fail-with-body https://gemini-ai-frontend.onrender.com/ &
        curl --fail-with-body https://gj-chat-app.onrender.com/ &
